## DATA ANALYSIS ON STUDENTS_CLEAN.CSV FILE

In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv("students_clean.csv")
df=pd.read_csv(r"students_clean.csv")

In [10]:
df.head()

   StudentID   Name Gender     City    JoinDate  Math  Science  English
0          1  Aditi      M    Delhi  2024-01-10  95.0     63.0     98.0
1          2  Rohan      F  Chennai  2024-01-19  62.0     77.0     77.0
2          3  Meera      F  Chennai  2024-01-28  45.0     76.0     61.0
3          4  Karan      M   Mumbai  2024-02-06  66.6     65.0     61.0
4          5  Sneha      M    Delhi  2024-02-15  75.0     89.0     61.0

In [7]:
# using group by
print(df.groupby('City')['Math'].mean().round(2))

City
Chennai    60.64
Delhi      73.58
Kolkata    68.00
Mumbai     68.94
Pune       64.96
Name: Math, dtype: float64

In [ ]:
#multiple aggregation in a single line using .agg
print(df.groupby('City')['Math'].agg(['count', 'min', 'max', 'median', 'std']).round(3))

         count   min   max  median     std
City
Chennai     11  42.0  88.0    62.0  16.458
Delhi        8  53.0  95.0    70.8  13.945
Kolkata      5  35.0  88.0    79.0  22.705
Mumbai       7  37.0  88.0    77.0  21.118
Pune         9  41.0  92.0    66.6  16.787

In [ ]:
#reset_index

In [11]:
# merge, concatenate, join
od=pd.read_csv("orders.csv")
cu=pd.read_csv("customers.csv")

In [12]:
od.head()

   OrderID  CustID     Product  Amount   OrderDate
0     1001     101      Laptop   55000  2026-01-05
1     1002     102  Headphones    2500  2026-01-08
2     1003     102     Monitor    9800  2026-01-15
3     1004     104    Keyboard    1200  2026-02-02
4     1005     107      Webcam    3200  2026-02-10

In [ ]:
cu.head()

   CustID          Name     City
0     101    Ananya Rao    Delhi
1     102    Bilal Khan   Mumbai
2     103   Chitra Iyer     Pune
3     104  Dev Malhotra  Chennai
4     105   Esha Kapoor  Kolkata

1. Merge (pd.merge)
When to use: When you want to combine two tables based on a shared column/key (in this case, matching the customer identifier, such as CustID). This is a relational join.

In [17]:
# Assuming the customer ID column in 'cu' is named 'CustID'
merged_df = pd.merge(od, cu, on="CustID", how="inner")
print(merged_df.head())

   OrderID  CustID     Product  Amount   OrderDate          Name     City
0     1001     101      Laptop   55000  2026-01-05    Ananya Rao    Delhi
1     1002     102  Headphones    2500  2026-01-08    Bilal Khan   Mumbai
2     1003     102     Monitor    9800  2026-01-15    Bilal Khan   Mumbai
3     1004     104    Keyboard    1200  2026-02-02  Dev Malhotra  Chennai
4     1006     101       Mouse     700  2026-02-14    Ananya Rao    Delhi

2. Join (df.join)
When to use: When you want to combine two DataFrames based on their Indices rather than specific columns.

If you want to use .join() using your customer identifier, you first need to set CustID as the index for both tables:

In [18]:
print(od.set_index('CustID').join(cu.set_index('CustID'), how="inner"))

        OrderID     Product  Amount   OrderDate          Name     City
CustID
101        1001      Laptop   55000  2026-01-05    Ananya Rao    Delhi
102        1002  Headphones    2500  2026-01-08    Bilal Khan   Mumbai
102        1003     Monitor    9800  2026-01-15    Bilal Khan   Mumbai
104        1004    Keyboard    1200  2026-02-02  Dev Malhotra  Chennai
101        1006       Mouse     700  2026-02-14    Ananya Rao    Delhi

DATE AND TIME